/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.administrativerole;

import Business.EcoSystem;
import Business.enterprise.Enterprise;
import Business.organization.Organization;
import Business.organization.PatientOrganization;
import Business.patient.Patient;
import Business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Romell
 */
public class PatientAnalytics extends javax.swing.JPanel {
     private JPanel userProcessContainer;
          private  Enterprise enterprise; 
          private  UserAccount account;
          public int max;
          private EcoSystem system;

    /**
     * Creates new form PatientAnalytics
     */
    

    PatientAnalytics(JPanel userProcessContainer, Enterprise enterprise, UserAccount account) {
     
        
    }

    PatientAnalytics(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, EcoSystem business) {
           initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.system=business;
        
    }
    public void prediction()
    {
        for (Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
        {PatientOrganization porg=null;
        
        if (organization instanceof PatientOrganization)
        { porg=(PatientOrganization)organization;
        for (Patient patient:porg.getPatientDirectory().getPatientDirectory())
        {
            max = Integer.MIN_VALUE;
            if(patient.getAbnormalNo() > max){
            max = patient.getAbnormalNo();
            }

          
            
        }
            }
        }
        for (Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
        {PatientOrganization porg=null;
        
        if (organization instanceof PatientOrganization)
        { porg=(PatientOrganization)organization;;
        for (Patient patient:porg.getPatientDirectory().getPatientDirectory())
        {
           if (patient.getAbnormalNo()==max)
           {JOptionPane.showMessageDialog(null, "Please do not use this medicine"+patient.getMedicine().toString());
               
           }

          
            
        }
            }
        }
        
    }
    
    
    public void populatetop10final()
           {int rowCount = tbl.getRowCount();
     DefaultTableModel model = (DefaultTableModel)tbl.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        } HashMap<String, Integer> hmap = new HashMap<String, Integer>();
        for (Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
        {PatientOrganization porg=null;
        
        if (organization instanceof PatientOrganization)
        { porg=(PatientOrganization)organization;
        for (Patient patient:porg.getPatientDirectory().getPatientDirectory())
         {System.out.println("ENTERED LOOP 1");
       
       
        hmap.put(patient.getName(), patient.getAbnormalNo());
        }
        }
        }
//        Set<Entry<Integer, String>> entries = hmap.entrySet();
//         TreeMap<Integer, String> sorted = new TreeMap<>(hmap);
//          Map<Integer, String> map = new TreeMap<Integer, String>(hmap); 
//          Set<Entry<Integer, String>> mappings = sorted.entrySet();
           
             Object[]a=hmap.entrySet().toArray();
             Arrays.sort(a, new Comparator() {
               @Override
               public int compare(Object o1, Object o2) {
                   return((Map.Entry<String,Integer>)o2).getValue().compareTo(((Map.Entry<String,Integer>)o1).getValue());
               }
           });
             for (Object e:a)
             {
             Object row[] = new Object[2];
//             for(Entry<Integer, String> mapping : mappings)
//             {
            row[0] = (((Map.Entry<String,Integer>)e).getKey());
          row[1] = (((Map.Entry<String,Integer>)e).getValue());
//            row[2] = orderItem.getQuantity();
//            row[3] = orderItem.getSales_price()*orderItem.getQuantity();
            
            model.addRow(row);
         }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        Predict = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Patients with frequent Heart Attacks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientName", "Frequency"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        Predict.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Predict.setText("Predict");
        Predict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PredictActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("                             Patient Analytics");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.PNG"))); // NOI18N

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(0, 51, 204));
        backjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backbutton.png"))); // NOI18N
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Predict, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backjButton1)
                        .addGap(317, 317, 317))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Predict, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populatetop10final();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PredictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PredictActionPerformed
        // TODO add your handling code here:
        prediction();
    }//GEN-LAST:event_PredictActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Predict;
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
